### ISSUE TITLE
Quat import error:

### ISSUE THREAD

**Issue by Burlollone** [Kapcash/ts-matrix#1]
In ts-matrix.d.ts there in an import error:

import Matrix from './Matrix';
import Quat from './Quat';
import Vector from './Vector';
export { Vector, Matrix, Quat, };

File ./Quat does not exist.
Exist ./quat

This creates a compilation error.
Can you fix it?

Thank you

**Comment by Kapcash** [comment]
Hi! Sorry for taking so long to fix this.

**It is fixed on v1.1.0! :)**

If you have any other feedback or bug, do not hesitate to open a new issue!
