### ISSUE TITLE
Need to add target: 'node in webpack config

### ISSUE THREAD

**Issue by jasonGranholt** [Kapcash/ts-matrix#2]
Hi, I got an error testing with jest, complaining 'window' is used. After adding ** target: 'node' ** in webpack.config.js, this was resolved.
```
const path = require('path');

module.exports = {
  entry: './src/ts-matrix.ts',
  devtool: 'inline-source-map',
  mode: 'production',
  target: 'node',
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: 'ts-loader',
        exclude: /node_modules/
      }
    ]
  },
  resolve: {
    extensions: ['.ts']
  },
  output: {
    library: 'tsmatrix',
    libraryTarget: 'umd',
    filename: 'tsmatrix.js',
    path: path.resolve(__dirname, 'dist')
  }
};
```

**Comment by Kapcash** [comment]
Hi! Good news, I switched from webpack to vite. The default target is `node` so in any case you should not have the problem anymore.

Please try to upgrade the library to [v1.2.0](https://github.com/Kapcash/ts-matrix/releases/tag/v1.2.0)
