### ISSUE TITLE
Error in matrix inverse()

### ISSUE THREAD

**Issue by jasonGranholt** [Kapcash/ts-matrix#3]
Hi, found a sign error in the matrix inverse, that the tests (only 1 inverse() test) did not catch. See inverse code below with the new fix added:

```
    inverse() {
        if (this.rows !== this.columns) throw new Error("The matrix isn't squared!");
        const det = this.determinant();
        if (det === 0) throw new Error("Determinant is 0, can't compute inverse.");

        // Get cofactor matrix
        let sign = -1;
        const cofactor = new Matrix (this.rows, this.columns,
            this.values.map((row, i) => row.map((val, j) => {
                sign = Math.pow(-1,i+j);           /////////////////////////////////// FIXED THIS LINE ////////////////
                return sign * this.getCofactor(i, j).determinant();
            })));
        // Transpose it
        const transposedCofactor = cofactor.transpose();
        // Compute inverse of transposed / determinant on each value
        return new Matrix(this.rows, this.columns,
            this.values.map((row, i) => row.map((val, j) => transposedCofactor.at(i, j) / det)));
    }
```

**Comment by Kapcash** [comment]
Feel free to open a Pull Request with your fix directly! So you could be the author of the fix commit ;)

Otherwise I'll review the change a soon as I have bandwith and fix this. Thanks you very much!

**Comment by Kapcash** [comment]
Thanks again for spotting the error, it's very appreciated!
The method wasn't tested enough indeed. It now tests on different matrix sizes (4 & 5).

I shipped the fix with version [v1.2.0](https://github.com/Kapcash/ts-matrix/releases/tag/v1.2.0). :)

**Comment by jasonGranholt** [comment]
Hi, the npm package for 1.2.0 does not have the inverse() fix, the compiled file in dist/ts-matrix.mjs still use the old code.

Could you check this? Thanks, Jason

**Comment by Kapcash** [comment]
You're right! I must have publish an old build dist/ by mistake 😅

Can you check with versions 1.2.1 or 1.2.2? They now includes sourcemaps and the src/ folder directly in the package so people can debug and take a look directly when installing :)

**Comment by jasonGranholt** [comment]
Thanks, it works now😊
