### ISSUE TITLE
`get rows()` and `get columns()` do not return arrays.

### ISSUE THREAD

**Issue by DanielRunningen** [Kapcash/ts-matrix#5]
The README says that these two getters should return arrays of their respective objects, but they currently return the sizes of each dimension instead.

https://github.com/Kapcash/ts-matrix/blob/ca38d57d9e97084e7545b761465ab7220ed6a8e2/src/Matrix.ts#L21C7-L21C7

**Comment by Kapcash** [comment]
Thank you for your feedback! It was indeed wrongly documented.
It's now updated and reflects what the getters actually do.
