### ISSUE TITLE
subtract, add, normalize - do they mutate or return new vector?

### ISSUE THREAD

**Issue by nataliefreed** [Kapcash/ts-matrix#6]
Thank you for this library!
The documentation says that subtract, add, and normalize mutate the current vector, but looking at and testing the code, these methods seem to return a new vector. Is the documentation correct for these?

**Comment by Kapcash** [comment]
Hi @nataliefreed! Thank you for the feedback.

No indeed, the documentation is outdated about that. I just updated it: these methods does return a new Vector instance and does not mutate the original one :)
